// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatPacket.proto

#ifndef PROTOBUF_ChatPacket_2eproto__INCLUDED
#define PROTOBUF_ChatPacket_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace ChatPacket {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ChatPacket_2eproto();
void protobuf_AssignDesc_ChatPacket_2eproto();
void protobuf_ShutdownFile_ChatPacket_2eproto();

class Chat;

// ===================================================================

class Chat : public ::google::protobuf::Message {
 public:
  Chat();
  virtual ~Chat();
  
  Chat(const Chat& from);
  
  inline Chat& operator=(const Chat& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Chat& default_instance();
  
  void Swap(Chat* other);
  
  // implements Message ----------------------------------------------
  
  Chat* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Chat& from);
  void MergeFrom(const Chat& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string ChatMessage = 1;
  inline bool has_chatmessage() const;
  inline void clear_chatmessage();
  static const int kChatMessageFieldNumber = 1;
  inline const ::std::string& chatmessage() const;
  inline void set_chatmessage(const ::std::string& value);
  inline void set_chatmessage(const char* value);
  inline void set_chatmessage(const char* value, size_t size);
  inline ::std::string* mutable_chatmessage();
  inline ::std::string* release_chatmessage();
  
  // @@protoc_insertion_point(class_scope:ChatPacket.Chat)
 private:
  inline void set_has_chatmessage();
  inline void clear_has_chatmessage();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* chatmessage_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_ChatPacket_2eproto();
  friend void protobuf_AssignDesc_ChatPacket_2eproto();
  friend void protobuf_ShutdownFile_ChatPacket_2eproto();
  
  void InitAsDefaultInstance();
  static Chat* default_instance_;
};
// ===================================================================


// ===================================================================

// Chat

// required string ChatMessage = 1;
inline bool Chat::has_chatmessage() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Chat::set_has_chatmessage() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Chat::clear_has_chatmessage() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Chat::clear_chatmessage() {
  if (chatmessage_ != &::google::protobuf::internal::kEmptyString) {
    chatmessage_->clear();
  }
  clear_has_chatmessage();
}
inline const ::std::string& Chat::chatmessage() const {
  return *chatmessage_;
}
inline void Chat::set_chatmessage(const ::std::string& value) {
  set_has_chatmessage();
  if (chatmessage_ == &::google::protobuf::internal::kEmptyString) {
    chatmessage_ = new ::std::string;
  }
  chatmessage_->assign(value);
}
inline void Chat::set_chatmessage(const char* value) {
  set_has_chatmessage();
  if (chatmessage_ == &::google::protobuf::internal::kEmptyString) {
    chatmessage_ = new ::std::string;
  }
  chatmessage_->assign(value);
}
inline void Chat::set_chatmessage(const char* value, size_t size) {
  set_has_chatmessage();
  if (chatmessage_ == &::google::protobuf::internal::kEmptyString) {
    chatmessage_ = new ::std::string;
  }
  chatmessage_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Chat::mutable_chatmessage() {
  set_has_chatmessage();
  if (chatmessage_ == &::google::protobuf::internal::kEmptyString) {
    chatmessage_ = new ::std::string;
  }
  return chatmessage_;
}
inline ::std::string* Chat::release_chatmessage() {
  clear_has_chatmessage();
  if (chatmessage_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = chatmessage_;
    chatmessage_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ChatPacket

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ChatPacket_2eproto__INCLUDED
