// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtocolPacket.proto

#ifndef PROTOBUF_ProtocolPacket_2eproto__INCLUDED
#define PROTOBUF_ProtocolPacket_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ProtocolPacket {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ProtocolPacket_2eproto();
void protobuf_AssignDesc_ProtocolPacket_2eproto();
void protobuf_ShutdownFile_ProtocolPacket_2eproto();

class Sample1;
class Sample2;
class Sample3;
class Sample4;

// ===================================================================

class Sample1 : public ::google::protobuf::Message {
 public:
  Sample1();
  virtual ~Sample1();

  Sample1(const Sample1& from);

  inline Sample1& operator=(const Sample1& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Sample1& default_instance();

  void Swap(Sample1* other);

  // implements Message ----------------------------------------------

  Sample1* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Sample1& from);
  void MergeFrom(const Sample1& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required float speed = 1;
  inline bool has_speed() const;
  inline void clear_speed();
  static const int kSpeedFieldNumber = 1;
  inline float speed() const;
  inline void set_speed(float value);

  // required float move = 2;
  inline bool has_move() const;
  inline void clear_move();
  static const int kMoveFieldNumber = 2;
  inline float move() const;
  inline void set_move(float value);

  // @@protoc_insertion_point(class_scope:ProtocolPacket.Sample1)
 private:
  inline void set_has_speed();
  inline void clear_has_speed();
  inline void set_has_move();
  inline void clear_has_move();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  float speed_;
  float move_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_ProtocolPacket_2eproto();
  friend void protobuf_AssignDesc_ProtocolPacket_2eproto();
  friend void protobuf_ShutdownFile_ProtocolPacket_2eproto();

  void InitAsDefaultInstance();
  static Sample1* default_instance_;
};
// -------------------------------------------------------------------

class Sample2 : public ::google::protobuf::Message {
 public:
  Sample2();
  virtual ~Sample2();

  Sample2(const Sample2& from);

  inline Sample2& operator=(const Sample2& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Sample2& default_instance();

  void Swap(Sample2* other);

  // implements Message ----------------------------------------------

  Sample2* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Sample2& from);
  void MergeFrom(const Sample2& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:ProtocolPacket.Sample2)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_ProtocolPacket_2eproto();
  friend void protobuf_AssignDesc_ProtocolPacket_2eproto();
  friend void protobuf_ShutdownFile_ProtocolPacket_2eproto();

  void InitAsDefaultInstance();
  static Sample2* default_instance_;
};
// -------------------------------------------------------------------

class Sample3 : public ::google::protobuf::Message {
 public:
  Sample3();
  virtual ~Sample3();

  Sample3(const Sample3& from);

  inline Sample3& operator=(const Sample3& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Sample3& default_instance();

  void Swap(Sample3* other);

  // implements Message ----------------------------------------------

  Sample3* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Sample3& from);
  void MergeFrom(const Sample3& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:ProtocolPacket.Sample3)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_ProtocolPacket_2eproto();
  friend void protobuf_AssignDesc_ProtocolPacket_2eproto();
  friend void protobuf_ShutdownFile_ProtocolPacket_2eproto();

  void InitAsDefaultInstance();
  static Sample3* default_instance_;
};
// -------------------------------------------------------------------

class Sample4 : public ::google::protobuf::Message {
 public:
  Sample4();
  virtual ~Sample4();

  Sample4(const Sample4& from);

  inline Sample4& operator=(const Sample4& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Sample4& default_instance();

  void Swap(Sample4* other);

  // implements Message ----------------------------------------------

  Sample4* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Sample4& from);
  void MergeFrom(const Sample4& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:ProtocolPacket.Sample4)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_ProtocolPacket_2eproto();
  friend void protobuf_AssignDesc_ProtocolPacket_2eproto();
  friend void protobuf_ShutdownFile_ProtocolPacket_2eproto();

  void InitAsDefaultInstance();
  static Sample4* default_instance_;
};
// ===================================================================


// ===================================================================

// Sample1

// required float speed = 1;
inline bool Sample1::has_speed() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Sample1::set_has_speed() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Sample1::clear_has_speed() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Sample1::clear_speed() {
  speed_ = 0;
  clear_has_speed();
}
inline float Sample1::speed() const {
  return speed_;
}
inline void Sample1::set_speed(float value) {
  set_has_speed();
  speed_ = value;
}

// required float move = 2;
inline bool Sample1::has_move() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Sample1::set_has_move() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Sample1::clear_has_move() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Sample1::clear_move() {
  move_ = 0;
  clear_has_move();
}
inline float Sample1::move() const {
  return move_;
}
inline void Sample1::set_move(float value) {
  set_has_move();
  move_ = value;
}

// -------------------------------------------------------------------

// Sample2

// -------------------------------------------------------------------

// Sample3

// -------------------------------------------------------------------

// Sample4


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProtocolPacket

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ProtocolPacket_2eproto__INCLUDED
