//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18444
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apedg
{
    
    
    public class ConstantSet
    {
        
        public const int PACKET_HEADER_SIZE = 6;
        
        public const int MAX_ID_LENGTH = 17;
        
        public const int MAX_PW_LENGTH = 17;
        
        public const int MAX_LOAD_TEST1_COUNT = 24;
        
        public const int MAX_LOAD_TEST2_COUNT = 24;
        
        public const int MAX_LOAD_QUEST_CODE_COUNT = 128;
        
        public const int MAX_CHARACTER_ITEM_COUNT = 32;
    }
    
    public class Header
    {
        
        public short RegionID;
        
        public short PacketID;
        
        public short BodySize;
    }
    
    public class PKTReqLogin
    {
        
        public short IDLength;
        
        public System.Collections.Generic.List<System.String> szID;
        
        public short PWLength;
        
        public System.Collections.Generic.List<System.String> szPW;
    }
    
    public class PKTResLogin
    {
        
        public short nResult;
        
        public long UserIndex;
    }
    
    public class PKTReqCharacterInfo
    {
        
        public int CharacterIndex;
    }
    
    public class PKTResCharacterInfo
    {
        
        public int HP;
        
        public float Exp;
    }
    
    public class PKTReqTest1
    {
        
        public long CharCode;
    }
    
    public class PKTResTest1
    {
        
        public long CharCode;
        
        public System.Collections.Generic.List<System.Int32> Tests;
    }
    
    public class PKTReqTest2
    {
        
        public long CharCode;
    }
    
    public class PKTResTest2
    {
        
        public short TestCount;
        
        public System.Collections.Generic.List<System.Int16> Tests;
    }
    
    public class PKTReqCompetedQuestCode
    {
        
        public long CharCode;
    }
    
    public class PKTResCompetedQuestCode
    {
        
        public long CharCode;
        
        public short QuestCodeCount;
        
        public System.Collections.Generic.List<System.Int16> QuestCodes;
    }
    
    public class PKTReqCharacterItem
    {
        
        public int CharacterIndex;
    }
    
    public class CharItem
    {
        
        public ulong Index;
        
        public short Level;
    }
    
    public class PKTResCharacterItem
    {
        
        public long CharCode;
        
        public CharItem Item;
    }
    
    public class PKTResCharacterItemArray
    {
        
        public short ItemCount;
        
        public System.Collections.Generic.List<CharItem> Items;
    }
}

